# Generated by Django 5.2.17 on 2026-09-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_projectform_project_project_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
    ]
